ecm_parameters:
  window_shgc: [0.2, 0.4, 0.6, 0.8] 
  window_u_value: [0.5, 1, 1.5, 2, 2.5, 3] # W/m²K
  visible_transmittance: [0.4, 0.6, 0.7]
  wall_insulation: [1, 2, 3, 4] # m²K/W
  infiltration_rate: [0.25, 0.5, 0.75, 1, 1.25, 1.5] # ACH
  natural_ventilation_area: [0.4, 0.8, 1.2, 1.6, 2, 2.4] # m²
  cooling_cop: [3.5, 4, 4.5, 5, 5.5, 6]
  heating_cop: [3.5, 4, 4.5, 5, 5.5, 6]
  cooling_air_temperature: [10, 12, 14, 16] # °C
  heating_air_temperature: [32, 34, 36, 40] # °C
  lighting_power_reduction_level: [1, 2, 3]