optimization:
  seed: 1

  genetic:
    generations: 200
    population_size: 200
    hall_of_fame_percentage: 0.05 # [0-1]
    # 个体级概率
    crossover_prob_start: 0.9
    crossover_prob_end: 0.6
    mutation_prob_start: 0.3
    mutation_prob_end: 0.05
    # 基因级概率
    gene_crossover_prob: 0.5
    gene_mutation_prob: 0.1